services:
  db:
    image: postgres
    # restart: always
    container_name: wordl
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=wordl
      - POSTGRES_DB=wordl
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password

secrets:
  db_password:
    file: ./postgres/config/db_password
